### PR TITLE
Add ability to specify additional roots for LESS processor

### PR DESCRIPTION
**Pull request by Fantast**
Currently, we can't specify additional roots for LESS resolving algorithm, even though less itself trivially supports it. This change tries to fix this.

### CODE REVIEW

**Comment by joeybaker** [comment]
Nice! Does it make sense to update the docs to mention this, or do you feel that the current wording is enough? https://github.com/atomify/atomify-css#opts-for-less-workflows

**Comment by Fantast** [comment]
I do think, it's enough. It was misleading earlier, making me think that it's already supported :) So, I think, now it should be fine.

**Comment by joeybaker** [comment]
Nifty! Thanks @Fantast!

**Comment by joeybaker** [comment]
Published as 3.3.5

**Pull request merged**
